// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW2YdAX_5beQrjkKmNyykTMqRixc-K88Y',
    appId: '1:566987559821:web:cf42ff2541a08c880ce3c4',
    messagingSenderId: '566987559821',
    projectId: 'my-taxi-app-bbc7c',
    authDomain: 'my-taxi-app-bbc7c.firebaseapp.com',
    storageBucket: 'my-taxi-app-bbc7c.firebasestorage.app',
    measurementId: 'G-F3J3N6LYS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhvGI9-UZaXDfzRytCrFUf4kz5zOp-buw',
    appId: '1:566987559821:android:f4b0a17b88a2a95f0ce3c4',
    messagingSenderId: '566987559821',
    projectId: 'my-taxi-app-bbc7c',
    storageBucket: 'my-taxi-app-bbc7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtDJ1SJiWZK3lDKmzhp8HU_TJo9Ibdvys',
    appId: '1:566987559821:ios:df774b154477afd40ce3c4',
    messagingSenderId: '566987559821',
    projectId: 'my-taxi-app-bbc7c',
    storageBucket: 'my-taxi-app-bbc7c.firebasestorage.app',
    iosBundleId: 'com.example.myTaxiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtDJ1SJiWZK3lDKmzhp8HU_TJo9Ibdvys',
    appId: '1:566987559821:ios:df774b154477afd40ce3c4',
    messagingSenderId: '566987559821',
    projectId: 'my-taxi-app-bbc7c',
    storageBucket: 'my-taxi-app-bbc7c.firebasestorage.app',
    iosBundleId: 'com.example.myTaxiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW2YdAX_5beQrjkKmNyykTMqRixc-K88Y',
    appId: '1:566987559821:web:23f92dcadb56c31b0ce3c4',
    messagingSenderId: '566987559821',
    projectId: 'my-taxi-app-bbc7c',
    authDomain: 'my-taxi-app-bbc7c.firebaseapp.com',
    storageBucket: 'my-taxi-app-bbc7c.firebasestorage.app',
    measurementId: 'G-V79SENZG6K',
  );
}
